# Generated by Django 4.2.3 on 2023-09-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0013_alter_picture_medium_img'),
        ('account', '0002_alter_bookmark_chapter_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reader.chapter', verbose_name=' '),
        ),
    ]
