# Generated by Django 4.2.3 on 2023-09-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0013_alter_picture_medium_img'),
        ('account', '0003_alter_bookmark_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reader.chapter', verbose_name=' '),
        ),
    ]
