services:
  mangalove_nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
        #expose:
        #- 80
    volumes:
      - static_files:/home/app/static
      - imgs:/home/app/imgs
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    #image: nginx:latest
    #command: rm /etc/nginx/conf.d/default.conf
    #ports:
    #- 80:80
    #- 443:443
    #restart: always
    #volumes:
    #- ./nginx/nginx.conf/:/etc/nginx/conf.d/:ro
    #- ./certbot/www:/var/www/certbot/:ro
    #- static_files:/home/app/static
    #- imgs:/home/app/imgs

  db:
    image: postgres 
    env_file:
      - .env.prod 
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    depends_on:
      - mangalove_nginx 

  backend_mangalove:
    build: .
    volumes:
      - static_files:/home/app/static
      - imgs:/home/app/imgs
    env_file:
      - .env.prod
    expose:
      - 8000
    command: gunicorn manga_reader.wsgi:application --bind 0.0.0.0:8000

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.prod
    volumes: 
      - cache:/data


volumes:
  pg_data:
  static_files:
  cache:
  imgs:
