# Generated by Django 4.2.4 on 2023-08-25 13:14

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to=reader.models.upload_to),
        ),
    ]
