# Generated by Django 4.2.4 on 2023-08-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_chapter_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
    ]
