# Generated by Django 4.2.4 on 2023-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_remove_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
