# Generated by Django 4.2.4 on 2023-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='slug',
            field=models.SlugField(default='dr-stone', max_length=200),
            preserve_default=False,
        ),
    ]
