# Generated by Django 4.2.3 on 2023-08-27 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='likes',
            field=models.ManyToManyField(related_name='liked_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось'),
        ),
    ]
