# Generated by Django 4.2.4 on 2023-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_chapter_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
