# Generated by Django 4.2.3 on 2023-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='poster',
            field=models.ImageField(blank=True, upload_to='manga_poster/'),
        ),
    ]
