# Generated by Django 4.2.3 on 2023-09-02 11:12

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_manga_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='medium_img',
            field=models.ImageField(default=1, upload_to=reader.models.upload_to_medium),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.FloatField(unique=True),
        ),
    ]
