# Generated by Django 4.2.3 on 2023-09-02 16:50

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_picture_medium_img_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='medium_img',
            field=models.ImageField(max_length=200, upload_to=reader.models.upload_to_medium),
        ),
    ]
