# Generated by Django 4.2.3 on 2023-09-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_manga_created_manga_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.FloatField(),
        ),
    ]
