# Generated by Django 4.2.3 on 2023-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0016_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mangatranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='manga',
            name='name',
            field=models.CharField(default='asdf', max_length=200, verbose_name='Название манги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangatranslation',
            name='description',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
