# Generated by Django 4.2.3 on 2023-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='medium_img',
            field=models.URLField(),
        ),
    ]
