# Generated by Django 4.2.3 on 2023-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0018_alter_picture_img_alter_picture_medium_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='medium_img',
            field=models.URLField(blank=True),
        ),
    ]
