# Generated by Django 4.2.3 on 2023-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0019_picture_picture_number_alter_picture_medium_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.URLField(),
        ),
    ]
